input {
  pipeline {
    address => "cold"
  }
}

output {
  http {
    url => "${COLD_BACKEND_URL}"
    http_method => "post"
    format => "json_batch"
    content_type => "application/json"
    pool_max => 50
    automatic_retries => 3
    retry_failed => true
  }
}
