input {
  elastic_agent {
    port => 5044
    ssl => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    ssl_certificate => "/usr/share/logstash/config/certs/logstash/logstash.crt"
    ssl_key => "/usr/share/logstash/config/certs/logstash/logstash.key"
    ssl_verify_mode => "force_peer"
  }
}

output {
  if [forensiq][path] == "hot" {
    pipeline {
      send_to => hot
    }
  } else if [forensiq][path] == "cold" {
    pipeline {
      send_to => cold
    }
  } else {
    pipeline {
      send_to => ["hot", "cold"]
    }
  }
}
