"""initial_schema

Revision ID: 5a4a9f8d935c
Revises: 
Create Date: 2026-03-24 12:46:28.637235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a4a9f8d935c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_check_id'), 'health_check', ['id'], unique=False)
    op.create_table('log_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('static_trust_level', sa.String(), nullable=False),
    sa.Column('dynamic_trust_score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('os_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_sources_agent_id'), 'log_sources', ['agent_id'], unique=True)
    op.create_index(op.f('ix_log_sources_static_trust_level'), 'log_sources', ['static_trust_level'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('virtual_ocsf_normalization',
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('raw_data_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('class_name')
    )
    op.create_table('access_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forensic_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('investigator_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sealed_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('log_count', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.LargeBinary(), nullable=False),
    sa.Column('merkle_root', sa.LargeBinary(), nullable=False),
    sa.Column('chain_hash', sa.LargeBinary(), nullable=False),
    sa.Column('tsa_token', sa.LargeBinary(), nullable=False),
    sa.Column('authoritative_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rsa_signature', sa.LargeBinary(), nullable=False),
    sa.Column('signing_key_id', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('logstash_config_version', sa.String(), server_default='v2.1.0', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['log_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'sequence_number', name='uq_sealed_blocks_source_sequence')
    )
    op.create_index('ix_sealed_blocks_authoritative_time', 'sealed_blocks', ['authoritative_time'], unique=False)
    op.create_index('ix_sealed_blocks_source_window', 'sealed_blocks', ['source_id', 'window_start', 'window_end'], unique=False)
    op.create_table('forensic_hypotheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('generation_source', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('hypotheses', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['forensic_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hot_cold_traces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_fingerprint', sa.String(), nullable=False),
    sa.Column('elastic_event_id', sa.String(), nullable=True),
    sa.Column('cold_offset', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['sealed_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hot_cold_traces_block_id'), 'hot_cold_traces', ['block_id'], unique=False)
    op.create_index(op.f('ix_hot_cold_traces_elastic_event_id'), 'hot_cold_traces', ['elastic_event_id'], unique=True)
    op.create_index(op.f('ix_hot_cold_traces_event_fingerprint'), 'hot_cold_traces', ['event_fingerprint'], unique=True)
    op.create_table('hypothesis_evidence_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('elastic_event_id', sa.String(), nullable=True),
    sa.Column('evidence_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['forensic_hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigator_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('investigator_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('reasoning_notes', sa.String(), nullable=True),
    sa.Column('ui_state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['forensic_cases.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['forensic_hypotheses.id'], ),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigator_decisions')
    op.drop_table('hypothesis_evidence_map')
    op.drop_index(op.f('ix_hot_cold_traces_event_fingerprint'), table_name='hot_cold_traces')
    op.drop_index(op.f('ix_hot_cold_traces_elastic_event_id'), table_name='hot_cold_traces')
    op.drop_index(op.f('ix_hot_cold_traces_block_id'), table_name='hot_cold_traces')
    op.drop_table('hot_cold_traces')
    op.drop_table('forensic_hypotheses')
    op.drop_index('ix_sealed_blocks_source_window', table_name='sealed_blocks')
    op.drop_index('ix_sealed_blocks_authoritative_time', table_name='sealed_blocks')
    op.drop_table('sealed_blocks')
    op.drop_table('forensic_cases')
    op.drop_table('access_audit_log')
    op.drop_table('virtual_ocsf_normalization')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_log_sources_static_trust_level'), table_name='log_sources')
    op.drop_index(op.f('ix_log_sources_agent_id'), table_name='log_sources')
    op.drop_table('log_sources')
    op.drop_index(op.f('ix_health_check_id'), table_name='health_check')
    op.drop_table('health_check')
    # ### end Alembic commands ###
