services:
  es01:
    dns:
      # Check with `cat /etc/resolv.conf` if using NetworkManager on Linux and paste entries here
      - 127.0.2.2
      - 127.0.2.3

  kib01:
    dns:
      - 127.0.2.2
      - 127.0.2.3

  fleet:
      dns:
        - 127.0.2.2
        - 127.0.2.3
