services:
  # Setup Automated Security & Certificates
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ ! -f config/certs/ca.zip ]; then
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo -ne "instances:\n  - name: es01\n    dns: [es01, localhost]\n  - name: kib01\n    dns: [kib01, localhost]\n  - name: fleet\n    dns: [fleet, localhost]\n  - name: logstash\n    dns: [logstash, localhost]\n" > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        chown -R 1000:1000 config/certs;
        echo "Waiting for ES...";
        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 5; done;
        echo "Setting kibana_system password...";
        curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}"
        echo "Setup complete. Keeping container alive for dependencies...";
        sleep infinity
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 5s
      retries: 20

  es01:
    depends_on:
      setup: { condition: service_healthy }
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock: { soft: -1, hard: -1 }
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 20

  kib01:
    depends_on:
      es01: { condition: service_healthy }
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - certs:/usr/share/kibana/config/certs
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - ${KIBANA_PORT}:5601
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - ES_URL=https://es01:9200
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 15s
      timeout: 10s
      retries: 20

  logstash:
    depends_on:
      es01: { condition: service_healthy }
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    ports:
      - 5044:5044
    volumes:
      - certs:/usr/share/logstash/config/certs:ro
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - lsdata:/usr/share/logstash/data
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  fleet:
    depends_on:
      kib01: { condition: service_healthy }
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    user: root
    volumes:
      - certs:/usr/share/elastic-agent/config/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_HOST=0.0.0.0
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - ELASTICSEARCH_HOST=https://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_CA=/usr/share/elastic-agent/config/certs/ca/ca.crt
      - KIBANA_FLEET_HOST=https://kib01:5601
      - KIBANA_FLEET_SETUP=1

# Volumes mounted and bound to ./volumes/ subdir
volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/../volumes/certs
  esdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/../volumes/esdata
  lsdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/../volumes/lsdata
